// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcgX7Yu8JOd0_rqdFO07R8ZEb7ybicSp0',
    appId: '1:900092231681:web:aa1884fe3e3325384c8000',
    messagingSenderId: '900092231681',
    projectId: 'chunha-b7db7',
    authDomain: 'chunha-b7db7.firebaseapp.com',
    storageBucket: 'chunha-b7db7.firebasestorage.app',
    measurementId: 'G-608LG5TDVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMGgOqlD5mnaFHqbw-M0vfu-ZaCcmxaKg',
    appId: '1:900092231681:android:6f9b25b462c04f634c8000',
    messagingSenderId: '900092231681',
    projectId: 'chunha-b7db7',
    storageBucket: 'chunha-b7db7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl_k5fXe54gbBDFpbO_WtTqZphyiAaqVQ',
    appId: '1:900092231681:ios:0ebeda1fceb86c0d4c8000',
    messagingSenderId: '900092231681',
    projectId: 'chunha-b7db7',
    storageBucket: 'chunha-b7db7.firebasestorage.app',
    androidClientId: '900092231681-qb0udta6i893ks8mm263nmu5543tg14e.apps.googleusercontent.com',
    iosClientId: '900092231681-q0h8sq29a6dsmhht7fvk31hk86tso0o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chunha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl_k5fXe54gbBDFpbO_WtTqZphyiAaqVQ',
    appId: '1:900092231681:ios:0ebeda1fceb86c0d4c8000',
    messagingSenderId: '900092231681',
    projectId: 'chunha-b7db7',
    storageBucket: 'chunha-b7db7.firebasestorage.app',
    androidClientId: '900092231681-qb0udta6i893ks8mm263nmu5543tg14e.apps.googleusercontent.com',
    iosClientId: '900092231681-q0h8sq29a6dsmhht7fvk31hk86tso0o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chunha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcgX7Yu8JOd0_rqdFO07R8ZEb7ybicSp0',
    appId: '1:900092231681:web:7f301d5f17fffb124c8000',
    messagingSenderId: '900092231681',
    projectId: 'chunha-b7db7',
    authDomain: 'chunha-b7db7.firebaseapp.com',
    storageBucket: 'chunha-b7db7.firebasestorage.app',
    measurementId: 'G-4KFQ70NGE7',
  );

}